### SGD_Classification

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.linear_model import SGDClassifier

In [3]:
X = [[0., 0.], [1., 1.]]
y = [0, 1]

In [4]:
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)

In [5]:
clf.fit(X , y)

C:\ANACONDA\Boris_Tondjua\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:570: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


SGDClassifier(max_iter=5)

In [6]:
clf.predict([[2., 2.]])

array([1])

In [7]:
# SGD fits a linear model to the training data. The coef_ attribute holds the model parameters:
clf.coef_

array([[9.91080278, 9.91080278]])

In [8]:
# The intercept_ attribute holds the intercept (aka offset or bias):
clf.intercept_

array([-9.99002993])

In [9]:
# The signed distance to the hyperplane (computed as the dot product between the coefficients and the input sample, plus the intercept) is given by 
# SGDClassifier.decision_function:
clf.decision_function([[2., 2.]])

array([29.65318117])

In [10]:
# Using loss="log" or loss="modified_huber" enables the predict_proba method, which gives a vector 
# of probability estimates per x sample :
clf = SGDClassifier(loss="log", max_iter=5).fit(X, y)
clf.predict_proba([[1., 1.]]) 

C:\ANACONDA\Boris_Tondjua\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:570: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


array([[0.00459185, 0.99540815]])

In [11]:
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [12]:
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
Y = np.array([1, 1, 2, 2])

In [13]:
# Always scale the input. The most convenient way is to use a pipeline.
clf = make_pipeline(StandardScaler(),
                  SGDClassifier(max_iter=1000, tol=1e-3))

In [14]:
clf.fit(X, Y) 

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier())])

In [15]:
print(clf.predict([[-0.8, -1]]))

[1]


### SGD_Regression

In [17]:
# A little bit Code from sklearn
from sklearn.datasets import make_regression